apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    isDefault: true
    url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
    editable: false