{
 "title": "app devOps dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(app_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests/sec",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(app_requests_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum(rate(app_request_duration_seconds_bucket[5m])) by (le)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(\n  container_memory_working_set_bytes{\n    namespace=\"primalabs\",\n    container=\"primalabs-app\"\n  }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    container_cpu_usage_seconds_total{\n      namespace=\"primalabs\",\n      container=\"primalabs-app\"\n    }[5m]\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Endpoint",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(path)(\n  rate(app_requests_total[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}